[package]
name = "sic"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "4.5.2"
derivative = "2.2.0"
dot = { git = "https://github.com/syntacticsugarglider/dot-rust", branch = "main" }
