name: Check 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        rustup default stable
        rustup update
    - name: Build
      run: cargo build --lib
    - name: Build with hardware acceleration
      run: cargo build --lib --features accelerated
    - name: Build with graphviz support
      run: cargo build --lib --features graphviz
    - name: Build with all features enabled
      run: cargo build --lib --features graphviz,accelerated
    - name: Run tests
      run: cargo test --features accelerated